moveit_simple_controller_manager:
  controller_names:
    - stick_arm_controller

  stick_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - swivel_link_joint
      - link1_link_joint
      - link2_link_joint
